// Resolve a manifest icon name (lucide-react identifier) to a component.
// Manifests carry icons as strings; the frontend maps them here. Unknown names
// fall back to a neutral glyph so a new tool never renders a broken nav item.

import {
  Home,
  Globe,
  Users,
  ShoppingCart,
  CalendarDays,
  Package,
  Wallet,
  Megaphone,
  BarChart3,
  IdCard,
  Settings,
  Pill,
  ClipboardList,
  ReceiptText,
  Truck,
  ShieldCheck,
  Sparkles,
  LayoutGrid,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  home: Home,
  dashboard: Home,
  globe: Globe,
  language: Globe,
  website: Globe,
  users: Users,
  group: Users,
  customers: Users,
  crm: Users,
  "shopping-cart": ShoppingCart,
  shopping_cart: ShoppingCart,
  orders: ShoppingCart,
  "calendar-days": CalendarDays,
  calendar_today: CalendarDays,
  calendar: CalendarDays,
  bookings: CalendarDays,
  package: Package,
  inventory_2: Package,
  inventory: Package,
  wallet: Wallet,
  payments: Wallet,
  megaphone: Megaphone,
  campaign: Megaphone,
  marketing: Megaphone,
  "bar-chart-3": BarChart3,
  analytics: BarChart3,
  "id-card": IdCard,
  badge: IdCard,
  staff: IdCard,
  settings: Settings,
  pill: Pill,
  prescriptions: ClipboardList,
  "clipboard-list": ClipboardList,
  pos: ReceiptText,
  "receipt-text": ReceiptText,
  truck: Truck,
  tracking: Truck,
  compliance: ShieldCheck,
  loyalty: Sparkles,
};

export const iconFor = (name?: string): LucideIcon =>
  (name && ICONS[name.toLowerCase()]) || LayoutGrid;
